var p=(r,s)=>()=>(s||r((s={exports:{}}).exports,s),s.exports);import{S as u}from"./assets/vendor-d5aa4654.js";var w=p((x,c)=>{(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d=new u(".gallery a",{overlayOpacity:8,captionData:"href",captionDelay:250,captionClass:"text-center"}),m=document.querySelector(".gallery"),i=document.querySelector(".form");i.addEventListener("submit",f);function f(r){r.preventDefault();const n=i.querySelector("input[type='text']").value;h(n).then(a=>{const e=a.hits;m.innerHTML=g(e),d.refresh()}).catch(a=>v(a.errorMsg)).finally(()=>i.reset())}const y="43197174-dcc5f5044572d8f441379a766";function h(r){const s=new URLSearchParams({key:y,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(n=>{if(!n.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return n.json()})}function g(r){return r.map(({webformatURL:s,largeImageURL:n,tags:a,likes:e,views:t,comments:o,downloads:l})=>`
    <ul class="list">
        <li class="list-item">
        <a class="gallery-link" href="${n}">
            <img  class="list-image" src="${s}" alt="${a}">
            <div class="image-details">          
                <p class="likes"><span class="span">Likes:</span><br> <span class="span-link">${e}</span> </p>
                <p class="views"><span class="span">Views:</span><br> <span class="span-link">${t}</span>  </p>                                
                <p class="comments"><span class="span">Comments:</span><br> <span class="span-link">${o}</span></p>               
                <p class="downloads"><span class="span">Downloads:</span><br> <span class="span-link">${l}</span></p>                           
            </div>
        </li>
    </ul>`).join("")}let b=document.getElementById("toastBox");function v(r){let s=document.createElement("div");s.classList.add("toast"),s.innerHTML=r,b.appendChild(s),setTimeout(()=>{s.remove()},5e3)}const L=require("path");c.exports={entry:"./src/index.js",output:{filename:"bundle.js",path:L.resolve(__dirname,"dist")},module:{rules:[{test:/\.css$/,use:["style-loader","css-loader"]}]}}});export default w();
//# sourceMappingURL=commonHelpers.js.map
